### ISSUE TITLE
Clarifying question about the model architecture

### ISSUE THREAD

**Issue by e-spaulding** [SapienzaNLP/unify-srl#5]
Hello,

I would like to clarify the model architecture being used here. I thought this code performed predicate identification, predicate sense disambiguation, argument identification and argument classification in a single forward pass, but it looks like the "forward" function takes the indices of the predicate already identified as input. ie, see line 94 of srl/models/model.py. 

I was hoping to emulate this model architecture for a similar task, but can't figure out how you go about predicate identification. Is the predicate identified before you encode and decode the sense and predicate-argument representations? If so, how?

Many thanks

**Comment by andreabac3** [comment]
Hi @e-spaulding,

what we wrote is correct, the network in a single forward pass performs both predicate identification/disambiguation and role classification.

As input, the network can receive the identified predicates because that's how the CoNLL-2009 task is defined.
All systems in the CoNLL benchmark are trained using pre-identified predicates as input.
Instead, we let the network learn to do predicate identification in a multi-task fashion, so we have a loss for predicate identification.

Kind regards,
Andrea Bacciu

**Comment by e-spaulding** [comment]
Thank you, this is very helpful!
